baseURL = 'https://ishaanpathak.github.io/'
languageCode = 'en-us'
title = 'Ishaan Pathak'
theme = 'digitalgarden'
[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/ishaanpathak'
  weight = 1
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/ishaan-pathak-17a620149'
  weight = 2
[[menu.social]]
  name = 'Email'
  url = 'mailto:pathakishaan@tutanota.com'
  weight = 3
